name: state_management_practice
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  uuid: ^4.5.1
  bloc_suite: ^0.0.5
  flutter_bloc: ^9.1.0
  provider: ^6.1.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
